[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/posts/"
to = "/.netlify/builders/instant"
status = 200
force = true

[[redirects]]
from = "/posts/*"
to = "/.netlify/builders/instant"
status = 200
force = true

[[redirects]]
from = "/preview/*"
to = "/.netlify/functions/preview"
status = 200
force = true
