[functions]
node_bundler = "esbuild"
external_node_modules = ["@11ty/eleventy", "@11ty/dependency-tree", "pug-filters"]

[functions.instant]
included_files = [
  "./netlify/functions/instant/**/*",
  "./netlify/functions/instant/.cache/**/*"
]

[functions.preview]
included_files = [
  "./netlify/functions/preview/**/*",
  "./netlify/functions/preview/.cache/**/*"
]

[[redirects]]
from = "/posts/"
to = "/.netlify/builders/instant"
status = 200
force = true

[[redirects]]
from = "/posts/*"
to = "/.netlify/builders/instant"
status = 200
force = true

[[redirects]]
from = "/preview/*"
to = "/.netlify/functions/preview"
status = 200
force = true
